### ISSUE TITLE
Setting credentials for Git

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/windows-installer#18]
I recently learned from @jennybc on the r-discuss [list][] that there is a way to store credentials for Git on Windows so that you don't have to repeatedly add your username and password when using HTTPS for interfacing with GitHub.

Would it be possible to avoid having attendees follow these [directions][] by instead having it automatically done via the Windows installer?

[list]: http://lists.software-carpentry.org/pipermail/r-discuss_lists.software-carpentry.org/2014-August/000135.html
[directions]: https://github.com/jennybc/2014-05-12-ubc/blob/gh-pages/ubc-r/session2.4_github_windows_credential.md

**Comment by wking** [comment]
On Sun, Mar 15, 2015 at 04:25:20PM -0700, Greg Wilson wrote:
> Closed #18.

Are we sure we're done with this?  I'm still in favor of using the
built-in store helper [1], but there hadn't been any feedback on that
approach.

[1]: https://github.com/swcarpentry/windows-installer/issues/18#issuecomment-52523412
