### ISSUE TITLE
conda is not fully functional under msysgit

### ISSUE THREAD

**Issue by moorepants** [swcarpentry/windows-installer#26]
I came across this and thought it's worth noting here because I had some students try to run unix commands in msysgit that ran python scripts which needed to be pinned to certain versions with a conda environment and it failed miserably.

The `activate.bat` script that works with Windows fails under the msysgit shell. See:

https://github.com/conda/conda/issues/747

And the bash script `activate` that ships with the *nix versions of conda don't run in msysgit due to reasons mentioned in the above issue.

So having SWC participants install the combination of msysgit + Anaconda leaves them with a broken conda in some sense, but this only becomes apparent when you try to use the activate script to switch conda environments.

I'm not necessarily requesting a fix here but just wanted to make this issue known.

**Comment by ethanwhite** [comment]
Thanks for reporting this @moorepants.

I think it's probably better placed under a different repo, as this one is just for the software the supports Windows' installations by installing and configuring nano and SQL, adding things to the path, etc. This isn't for the Windows' installation stack more generally. That said, I'm not sure exactly where it should go, maybe https://github.com/swcarpentry/workshop-template.

My personal take on this is that the goal of our stack isn't to provide a perfect working environment for all students in the long-run. The point of our stack is something easy to set up that will work for all learners during the workshop for most learners for a reasonable period of time thereafter. Folks on any platform using sufficiently complex tools/workflows (including things like `activate`) will always outgrow these installs, at which point they will (hopefully) be sophisticated enough to navigate the challenges (in this case simply running `activate` from cmd).

Hopefully https://github.com/conda/conda/pull/913 will get in soon and this won't be an issue anyway.

**Comment by moorepants** [comment]
Thanks for the reply. Just wanted to have this noted.
