### ISSUE TITLE
Make on windows

### ISSUE THREAD

**Issue by wrightaprilm** [swcarpentry/windows-installer#34]
Hi Y'all-

We're having some issues with make on windows. The make.exe is in the ~/.swc/bin, which is in the path like it ought to be. Typing

```UNIX
ls ~/.swc/bin/
```
returns make.exe and nosetests.

But when we try to access Make from the command line, we get the error: 

error while loading shared libraries: cannot open shared object file: No such file or directory.

Has anyone had this issue?

**Comment by wking** [comment]
On Tue, Nov 17, 2015 at 07:23:25AM -0800, April Wright wrote:
> error while loading shared libraries: cannot open shared object
> file: No such file or directory.

Does Windows have an equivalent to strace [1] that would let you
figure out which shared libraries are missing?  My guess is that this
is the result of the msysGit → Git for Windows transition, and that
you want a Make built for MSys2 [2,3].  Does the Git for Windows
install add Packman to your path [3]?

[1]: https://en.wikipedia.org/wiki/Strace
[2]: https://github.com/git-for-windows/build-extra#msys2
[3]: https://msys2.github.io/

**Comment by wrightaprilm** [comment]
I'm not really sure if Windows has Strace. A cursory google indicates that there are some similar utilities. I don't actually have access to a PC on a regular basis, and I'm doing an alternate activity to the Make activity (~75% of my audience today is PC). If the case is that the transition from msys to GfW is the issue, then I think we need to switch over in the instructions and installer to use whichever is more complete. As it stands now, no PC users in the room had Make, unless they already had it for their own work.

**Comment by ethanwhite** [comment]
I can replicate on this. The fuller error message is:

`The program can't start because msys-1.0.dll is missing from your computer.`

**Comment by wking** [comment]
On Wed, Nov 18, 2015 at 07:39:58AM -0800, Ethan White wrote:
> I can replicate on this. The fuller error message is:
> 
> `The program can't start because msys-1.0.dll is missing from your
> computer.`

Heh, and that's with the old msysGit binary?  If you install a current
Git for Windows do you have ‘packman’ in your path?  It looks like the
old msysGit would build and distribute that library [1], but didn't
commit a compiled version to their Git history.

[1]: https://github.com/msysgit/msysgit/blob/master/src/rt/release.sh#L47-L70

**Comment by ethanwhite** [comment]
> Heh, and that's with the old msysGit binary?

This is following the current instructions using Git for Windows.

> If you install a current Git for Windows do you have ‘packman’ in your path? 

No.

**Comment by wking** [comment]
On Wed, Nov 18, 2015 at 11:02:39AM -0800, Ethan White wrote:
> > Heh, and that's with the old msysGit binary?
> 
> This is following the current instructions using Git for Windows.

Right, but your make.exe is from the old msysGit repository (e.g. as
installed by the installation script in this repository)?

> > If you install a current Git for Windows do you have ‘packman’ in
> > your path?
> 
> No.

Ah, it's ‘pacman’ [1].  Any luck with that?

[1]: https://msys2.github.io/

**Comment by ethanwhite** [comment]
> Right, but your make.exe is from the old msysGit repository (e.g. as installed by the installation script in this repository)?

Ah yes, sorry for the confusion.

> Ah, it's ‘pacman’ [1]. Any luck with that?

`pacman` is actually what I checked for.

**Comment by wking** [comment]
On Wed, Nov 18, 2015 at 11:20:33AM -0800, Ethan White wrote:
> > Ah, it's ‘pacman’ [1]. Any luck with that?
> 
> `pacman` is actually what I checked for.

Bummer.  So I think we need to:

* Remove install_msysgit_binary and the make.exe install from our
  script.
* Figure out how to install Make with pacman, via one of:
  a. Have students install MSys2 directly [1].
  b. Have students install the Git for Windows SDK [2].
  c. Follow the Git for Windows SDK example [3] and update our Inno
     Setup installer to use pacman to install Make for students.

For folks who need Make, both (a) and (b) are viable now (and (b) is a
larger install, but just one install for both Git and Make).  (c)
would be nice, but I don't have the time or Windows machine needed to
figure it out.  Depending on how troublesome (a) and (b) are, SWC
might want to fund someone to make (c) happen.

[1]: https://msys2.github.io/
[2]: https://github.com/git-for-windows/build-extra/releases 
[3]: https://github.com/git-for-windows/build-extra/blob/git-sdk-1.0.1/sdk-installer/setup-git-sdk.bat#L43-L46

**Comment by ethanwhite** [comment]
It looks like there might be an alternative. I just installed GNU Make for Windows [1] and it seems to be working for me. I installed it using the `Setup` installer, but presumably we could download the binaries in the same way we currently do.

[1] http://gnuwin32.sourceforge.net/packages/make.htm

**Comment by wking** [comment]
On Wed, Nov 18, 2015 at 12:45:50PM -0800, Ethan White wrote:
> It looks like there might be an alternative. I just installed GNU
> Make for Windows [1] and it seems to be working for me. I installed
> it using the `Setup` installer, but presumably we could download the
> binaries in the same way we currently do.

Ah, that works.  I'm not sure how alive it is (it's at GNU Make 3.81,
and that was cut on 2006-04-01 [1]), but it is probably the cheapest
short-term fix.

[1]: http://git.savannah.gnu.org/cgit/make.git/tag/?id=3.81

**Comment by ethanwhite** [comment]
> Ah, that works. I'm not sure how alive it is (it's at GNU Make 3.81, and that was cut on 2006-04-01 [1]), but it is probably the cheapest short-term fix.

Yeah, it's definitely stuck at where it is, but after experimenting with the other options I think it's a reasonable fix for the moment. Do you have some time to look at swapping this in to the Python script. I'd be happy to test.

**Comment by wking** [comment]
On Thu, Nov 19, 2015 at 07:33:00AM -0800, Ethan White wrote:
> Do you have some time to look at swapping this in to the Python
> script.

Should be done in #35.  We'll probably also want to test/merge #36
before cutting a new release.

**Comment by wking** [comment]
#35 has landed and we cut v0.3 with the new code, so I'm closing this.
Please reopen if there is more trouble :).
