### ISSUE TITLE
Issues with R paths

### ISSUE THREAD

**Issue by ethanwhite** [swcarpentry/windows-installer#44]
At a workshop I just ran we ran into issues with R not being in the path on a number of Windows computers. In the past this has been caused because R likes to change the path where it installs itself and we've needed to change the function that searches for R. The new path that is causing issues is:

`C:\Program Files\R\R-3.2.4revised\bin`

**Comment by embray** [comment]
Fantastic.  Does R not install its path in `%PATH%` when you install it?

**Comment by evanwill** [comment]
If we already have people installing Python via Anaconda, we could add R via conda which might simplify things. https://www.continuum.io/blog/developer/jupyter-and-conda-r

**Comment by embray** [comment]
Does the R package for conda include R Studio?  How much do the R workshops rely on R Studio, or do they use Jupyter more?

**Comment by evanwill** [comment]
No, Conda does not have RStudio. I just tested it this morning on a windows machine and realized its not so easy. The conda r-essentials works great for Jupyter notebook, and is available on the command line, but I can't get RStudio to run correctly with it. 
I think it maybe a permissions issue? Anaconda is installed for a user, not admin, so the conda R version is in `/Users/exampleuser/AppData/Local/Continuum/Anaconda3/`. By default RStudio only looks for R installed via a windows installer. I can set the path to the conda version, but it doesn't seem to actually work. 
So unless someone figures out how to make it work with RStudio, I guess its not helpful. 
However, using conda r-essentials is the easiest way to make R available to Jupyter notebook.

**Comment by fmichonneau** [comment]
The naming scheme for "R-3.2.4-revised" was an exception and R maintainers (relatively) quickly realized that it wasn't a good idea to come up with a naming scheme that was never used before. They soon after released 3.2.5 and probably won't use this naming scheme ever again (see the 3.2.5 release notes https://stat.ethz.ch/pipermail/r-announce/2016/000601.html). They even removed 3.2.4-revised from the list of previous releases.

**Comment by embray** [comment]
Fixed by #46.  Going to try to build a new version of the installer ASAP.
